import type { Metadata } from "next";
import "./globals.css";
import { Geist } from "next/font/google";
import { cn } from "../lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
    <html lang="es" className={cn("dark font-sans", geist.variable)} >
      <body>
        <div className="h-dvh bg-background overflow-hidden p-4">

          <main className="overflow-auto border h-full bg-card rounded-2xl">
            {children}
          </main>

        </div>
      </body>
    </html>
  
  );
}
