import type { Metadata } from "next";
import "./globals.css";
import { Geist } from "next/font/google";
import { cn } from "../lib/utils";
import { Toaster } from "sonner";
import { ThemeProvider } from "../components/theme-provider";
import { ThemeToggle } from "@/components/ui/theme-toggle";
import { NavigationWrapper } from "@/components/navigation-wrapper";
import { AuthProvider } from "@/components/auth-provider";
import { AuthSync } from "@/components/auth-sync";
import { AppDataProvider } from "@/components/app-data-provider";
import PageTransition from "@/components/page-transition";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  maximumScale: 1, // Disable auto-zoom on mobile Safari
  interactiveWidget: "resizes-content" as const,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={cn(" font-sans", geist.variable)}
      lang="es"
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <AuthSync />
            <AppDataProvider>
              <div className="h-dvh bg-background overflow-hidden p-2 flex flex-col gap-4">
                <main className="overflow-auto border flex-1 bg-card rounded-2xl relative">
                  <div className="min-h-full p-4">
                    <PageTransition>{children}</PageTransition>
                  </div>
                </main>
                <div className="h-fit">
                  <NavigationWrapper />
                </div>
                <Toaster position="top-center" />
              </div>
            </AppDataProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
